---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: unapp
  labels:
    app: unapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: unapp
    spec:
      containers:
      - name: unapp
        image: nginx:alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
